name: Build Android APK (example)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter (3.27.0 stable)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
          channel: stable

      - name: Flutter version check
        run: flutter --version

      - name: Get flutter packages
        working-directory: ./example
        run: flutter pub get

      - name: Build release APK
        working-directory: ./example
        run: flutter build apk --release

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: example/build/app/outputs/flutter-apk/app-release.apk

      - name: Build debug APK
        working-directory: ./example
        run: flutter build apk --debug

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: example/build/app/outputs/flutter-apk/app-debug.apk
